name: cloudrun-deploy
on:
  push:
    branches:
      - main
jobs:
    deploy:
      name: Setup Gcloud Account
      runs-on: ubuntu-latest
      env:
        IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: Build image
        run: 
          gcloud config set project ${{ secrets.GCP_PROJECT }} &&
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }} &&
          gcloud builds submit --pack image=gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }} &&
          gcloud config set run/region ${{ secrets.GCP_REGION }}
      - name: Deploy image
        run:
          gcloud config set project ${{ secrets.GCP_PROJECT }} &&
          gcloud run services update ${{ secrets.GCP_PROJECT }} --platform managed --region {{ secrets.GCP_REGION }} --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}